# Auto-generated by pydicom-data-sr
# -*- coding: utf-8 -*-

from typing import Dict, List, Tuple


concepts_PUBCHEM_CID: Dict[str, Dict[str, Tuple[str, List[int]]]] = {
    "_6Hydroxydopamine": {
        "4624": ("6-hydroxydopamine", [638, 643]),
    },
}
