# Auto-generated by pydicom-data-sr
# -*- coding: utf-8 -*-

from typing import Dict, List, Tuple


concepts_NDC: Dict[str, Dict[str, Tuple[str, List[int]]]] = {
    "Definity": {
        "11994-011-04": ("Definity", [12030]),
    },
    "Optison": {
        "0407-2707-03": ("Optison", [12030]),
    },
}
