# Auto-generated by pydicom-data-sr
# -*- coding: utf-8 -*-

concepts_MSH = {
    "LactatedRingerS": {
        "D000077325": ("Lactated Ringer's", [70, 3850]),
    },
    "MonteCarloMethod": {
        "D009010": ("Monte Carlo Method", [10068]),
    },
    "Technetium99mTRODAT1": {
        "C104196": ("Technetium^99m^ TRODAT-1", [25]),
    },
    "_18FluorineFlortaucipir": {
        "C000591008": ("^18^Fluorine flortaucipir", [4021]),
    },
}
