# Auto-generated by pydicom-data-sr
# -*- coding: utf-8 -*-

from typing import Dict, List, Tuple


concepts_ITIS_TSN: Dict[str, Dict[str, Tuple[str, List[int]]]] = {
    "PeromyscusLeucopus": {
        "180278": ("Peromyscus leucopus", [7454]),
    },
    "PeromyscusManiculatus": {
        "180276": ("Peromyscus maniculatus", [7454]),
    },
    "SigmodonGenus": {
        "180346": ("Sigmodon genus", [7454]),
    },
}
