# Auto-generated by pydicom-data-sr
# -*- coding: utf-8 -*-

concepts_UMLS = {
    "Alphaxalone": {
        "C0051482": ("Alphaxalone", [623, 625]),
    },
    "AnesthesiaRecoveryPeriod": {
        "C0002908": ("Anesthesia recovery period", [634]),
    },
    "Antihypoglycemic": {
        "C1579431": ("Antihypoglycemic", [621, 622]),
    },
    "Baseline": {
        "C1442488": ("Baseline", [6146]),
    },
    "CoefficientOfVariance": {
        "C0681921": ("Coefficient of Variance", [7464]),
    },
    "CommercialProduct": {
        "C1547887": ("Commercial product", [608]),
    },
    "ConsultingPhysician": {
        "C1441532": ("Consulting Physician", [7450, 7452, 9536, 9555, 9562]),
    },
    "DistalPhalanx": {
        "C3669027": ("Distal phalanx", [7482, 7483, 8134]),
    },
    "EdotreotideGa68": {
        "C2713594": ("Edotreotide Ga^68^", [4021]),
    },
    "EthidiumBromide": {
        "C0019873": ("Ethidium Bromide", [638, 643]),
    },
    "Fluanisone": {
        "C0060473": ("Fluanisone", [623, 625]),
    },
    "FluoroestradiolFESF18": {
        "C1831937": ("Fluoroestradiol (FES) F^18^", [4021]),
    },
    "FluoroetanidazoleF18": {
        "C1541539": ("Fluoroetanidazole F^18^", [4021]),
    },
    "FluoropropylDihydrotetrabenazineDTBZF18": {
        "C2934038": ("Fluoropropyl-dihydrotetrabenazine (DTBZ) F^18^", [4021]),
    },
    "H2Antagonist": {
        "C0019593": ("H2 antagonist", [621, 622]),
    },
    "HeatLamp": {
        "C0181514": ("Heat lamp", [635]),
    },
    "ISO1F18": {
        "C2981788": ("ISO-1 F^18^", [4021]),
    },
    "InfantOfMotherWithGestationalDiabetes": {
        "C0456029": ("Infant of mother with gestational diabetes", [3756]),
    },
    "Intern": {
        "C1144859": ("Intern", [7450, 7452]),
    },
    "InverseRatioVentilation": {
        "C2223982": ("Inverse ratio ventilation", [619, 620]),
    },
    "KevlarAramidFiber": {
        "C0064329": ("Kevlar Aramid Fiber", [10067]),
    },
    "MK6240F18": {
        "C4506764": ("MK-6240 F^18^", [4021]),
    },
    "Mastectomy": {
        "C0024881": ("Mastectomy", [6058, 6060]),
    },
    "MedicalPhysicist": {
        "C1708969": ("Medical Physicist", [7450, 7452, 9536, 9555, 9562]),
    },
    "Metomidate": {
        "C0025856": ("Metomidate", [623, 625]),
    },
    "Nadir": {
        "C1708760": ("Nadir", [6146]),
    },
    "NarcoticAnalgesic": {
        "C0027409": ("Narcotic analgesic", [621, 622]),
    },
    "Neuroradiology": {
        "C2183225": ("Neuroradiology", [7030]),
    },
    "PK1119511C": {
        "C1609883": ("PK11195 ^11^C", [4021]),
    },
    "Pretreatment": {
        "C3539075": ("Pretreatment", [6146]),
    },
    "RadiationPhysicist": {
        "C2985483": ("Radiation Physicist", [7450, 7452, 9536, 9555, 9562]),
    },
    "Referring": {
        "C1709880": ("Referring", [7453]),
    },
    "RestrictedDiet": {
        "C0425422": ("Restricted diet", [609]),
    },
    "RoomAir": {
        "C3846005": ("Room air", [623, 629]),
    },
    "RootMeanSquare": {
        "C2347976": ("Root Mean Square", [7464]),
    },
    "Sonographer": {
        "C1954848": ("Sonographer", [7450, 7452]),
    },
    "THK5317F18": {
        "C4550127": ("THK5317 F^18^", [4021]),
    },
    "THK5351F18": {
        "C4279748": ("THK5351 F^18^", [4021]),
    },
    "Thermography": {
        "C0039810": ("Thermography", [636]),
    },
    "TransgenicAnimal": {
        "C0003069": ("Transgenic animal", [602]),
    },
    "Tyrosine3OctreotateGa68": {
        "C1742831": ("tyrosine-3-octreotate Ga^68^", [4021]),
    },
    "UCBJC11": {
        "C4506788": ("UCB-J C^11^", [4021]),
    },
    "UnknownPrimaryNeoplasiaSite": {
        "C0221297": ("unknown primary neoplasia site", [7601, 8134]),
    },
    "Unscheduled": {
        "C1699701": ("Unscheduled", [6146]),
    },
    "Variance": {
        "C1711260": ("Variance", [7464]),
    },
}
