# Auto-generated by pydicom-data-sr
# -*- coding: utf-8 -*-

from typing import Dict, List, Tuple


concepts_IBSI: Dict[str, Dict[str, Tuple[str, List[int]]]] = {
    "AngularSecondMomentOfGLCM": {
        "8ZQL": ("Angular Second Moment of GLCM", [218, 7467, 7468]),
    },
    "AreaDensityInApproximateEnclosingEllipsoid": {
        "RDD2": ("Area Density in Approximate Enclosing Ellipsoid", [218, 7477]),
    },
    "AreaDensityInConvexHull": {
        "7T7F": ("Area Density in Convex Hull", [218, 7477]),
    },
    "AreaDensityInFrameOfReferenceAxisAlignedBoundingBox": {
        "R59B": (
            "Area Density in Frame of Reference Axis Aligned Bounding Box",
            [218, 7477],
        ),
    },
    "AreaDensityInMinimumVolumeEnclosingEllipsoid": {
        "BRI8": ("Area Density in Minimum Volume Enclosing Ellipsoid", [218, 7477]),
    },
    "AreaDensityInOrientedMinimumBoundingBox": {
        "IQYR": ("Area Density in Oriented Minimum Bounding Box", [218, 7477]),
    },
    "Asphericity": {
        "25C7": ("Asphericity", [218, 7477]),
    },
    "AutocorrelationOfGLCM": {
        "QWB0": ("Autocorrelation of GLCM", [218, 7467, 7468]),
    },
    "BusynessOfNGTDM": {
        "NQ30": ("Busyness of NGTDM", [218, 7468, 7500]),
    },
    "CentreOfMassShift": {
        "KLMA": ("Centre of Mass Shift", [218, 7477]),
    },
    "ClusterProminenceOfGLCM": {
        "AE86": ("Cluster Prominence of GLCM", [218, 7467, 7468]),
    },
    "ClusterShadeOfGLCM": {
        "7NFM": ("Cluster Shade of GLCM", [218, 7467, 7468]),
    },
    "ClusterTendencyOfGLCM": {
        "DG8W": ("Cluster Tendency of GLCM", [218, 7467, 7468]),
    },
    "CoarsenessOfNGTDM": {
        "QCDE": ("Coarseness of NGTDM", [218, 7468, 7500]),
    },
    "Compactness1": {
        "SKGS": ("Compactness 1", [218, 7477]),
    },
    "Compactness2": {
        "BQWJ": ("Compactness 2", [218, 7477]),
    },
    "ComplexityOfNGTDM": {
        "HDEZ": ("Complexity of NGTDM", [218, 7468, 7500]),
    },
    "ContrastOfGLCM": {
        "ACUI": ("Contrast of GLCM", [218, 7467, 7468]),
    },
    "ContrastOfNGTDM": {
        "65HE": ("Contrast of NGTDM", [218, 7468, 7500]),
    },
    "CorrelationOfGLCM": {
        "NI2N": ("Correlation of GLCM", [218, 7467, 7468]),
    },
    "DependenceCountEnergy": {
        "CAS9": ("Dependence count energy", [218, 7468, 7501]),
    },
    "DependenceCountEntropy": {
        "FCBV": ("Dependence count entropy", [218, 7468, 7501]),
    },
    "DependenceCountNonUniformity": {
        "Z87G": ("Dependence count non-uniformity", [218, 7468, 7501]),
    },
    "DependenceCountNonUniformityNormalized": {
        "OKJI": ("Dependence count non-uniformity normalized", [218, 7468, 7501]),
    },
    "DependenceCountPercentage": {
        "6XV8": ("Dependence count percentage", [218, 7468, 7501]),
    },
    "DependenceCountVariance": {
        "DNX2": ("Dependence count variance", [218, 7468, 7501]),
    },
    "DifferenceAverageOfGLCM": {
        "TF7R": ("Difference Average of GLCM", [218, 7467, 7468]),
    },
    "DifferenceEntropyOfGLCM": {
        "NTRS": ("Difference Entropy of GLCM", [218, 7467, 7468]),
    },
    "DifferenceVarianceOfGLCM": {
        "D3YU": ("Difference Variance of GLCM", [218, 7467, 7468]),
    },
    "DissimilarityOfGLCM": {
        "8S9J": ("Dissimilarity of GLCM", [218, 7467, 7468]),
    },
    "DistanceZonePercentage": {
        "VIWW": ("Distance Zone Percentage", [218, 7468, 7479]),
    },
    "Elongation": {
        "Q3CK": ("Elongation", [218, 7477]),
    },
    "FirstMeasureOfInformationCorrelationOfGLCM": {
        "R8DG": ("First Measure of Information Correlation of GLCM", [218, 7467, 7468]),
    },
    "Flatness": {
        "N17B": ("Flatness", [218, 7477]),
    },
    "GearyCMeasure": {
        "NPT7": ("Geary's C Measure", [218, 7477]),
    },
    "GrayLevelNonuniformityInRuns": {
        "R5YN": ("Gray Level Nonuniformity in Runs", [218, 7468, 7475]),
    },
    "GrayLevelNonuniformityOfSizeZoneCounts": {
        "JNSA": ("Gray Level Nonuniformity of Size Zone Counts", [218, 7468, 7476]),
    },
    "GrayLevelVarianceInRuns": {
        "8CE5": ("Gray Level Variance in Runs", [218, 7468, 7475]),
    },
    "GrayLevelVarianceInSizeZones": {
        "BYLV": ("Gray Level Variance in Size Zones", [218, 7468, 7476]),
    },
    "GreyLevelNonUniformityOfDistanceZoneCounts": {
        "VFT7": (
            "Grey Level Non-uniformity of Distance Zone Counts",
            [218, 7468, 7479],
        ),
    },
    "GreyLevelNonUniformityOfNGLDM": {
        "FP8K": ("Grey level non-uniformity of NGLDM", [218, 7468, 7501]),
    },
    "GreyLevelVarianceInDistanceZones": {
        "QK93": ("Grey Level Variance in Distance Zones", [218, 7468, 7479]),
    },
    "GreyLevelVarianceOfNGLDM": {
        "1PFV": ("Grey level variance of NGLDM", [218, 7468, 7501]),
    },
    "HighDependenceEmphasis": {
        "IMOQ": ("High dependence emphasis", [218, 7468, 7501]),
    },
    "HighDependenceHighGreyLevelEmphasis": {
        "9QMG": ("High dependence high grey level emphasis", [218, 7468, 7501]),
    },
    "HighDependenceLowGreyLevelEmphasis": {
        "NBZI": ("High dependence low grey level emphasis", [218, 7468, 7501]),
    },
    "HighGrayLevelRunEmphasis": {
        "G3QZ": ("High Gray Level Run Emphasis", [218, 7468, 7475]),
    },
    "HighGrayLevelZoneEmphasis": {
        "5GN9": ("High Gray Level Zone Emphasis", [218, 7468, 7476]),
    },
    "HighGreyLevelCountEmphasis": {
        "OAE7": ("High grey level count emphasis", [218, 7468, 7501]),
    },
    "HighGreyLevelZoneEmphasis": {
        "K26C": ("High Grey Level Zone Emphasis", [218, 7468, 7479]),
    },
    "IntegratedIntensity": {
        "99N0": ("Integrated Intensity", [218, 7477]),
    },
    "IntensityHistogram10thPercentile": {
        "GPMT": ("Intensity Histogram 10th Percentile", [218, 7468, 7478]),
    },
    "IntensityHistogram90thPercentile": {
        "OZ0C": ("Intensity Histogram 90th Percentile", [218, 7468, 7478]),
    },
    "IntensityHistogramCoefficientOfVariation": {
        "CWYJ": ("Intensity Histogram Coefficient of Variation", [218, 7468, 7478]),
    },
    "IntensityHistogramEntropy": {
        "TLU2": ("Intensity Histogram Entropy", [218, 7468, 7478]),
    },
    "IntensityHistogramInterquartileRange": {
        "WR0O": ("Intensity Histogram Interquartile Range", [218, 7468, 7478]),
    },
    "IntensityHistogramKurtosis": {
        "C3I7": ("Intensity Histogram Kurtosis", [218, 7468, 7478]),
    },
    "IntensityHistogramMaximumGradient": {
        "12CE": ("Intensity Histogram Maximum Gradient", [218, 7468, 7478]),
    },
    "IntensityHistogramMaximumGradientGrayLevel": {
        "8E6O": ("Intensity Histogram Maximum Gradient Gray Level", [218, 7468, 7478]),
    },
    "IntensityHistogramMaximumGrayLevel": {
        "3NCY": ("Intensity Histogram Maximum Gray Level", [218, 7468, 7478]),
    },
    "IntensityHistogramMean": {
        "X6K6": ("Intensity Histogram Mean", [218, 7468, 7478]),
    },
    "IntensityHistogramMeanAbsoluteDeviation": {
        "D2ZX": ("Intensity Histogram Mean Absolute Deviation", [218, 7468, 7478]),
    },
    "IntensityHistogramMedian": {
        "WIFQ": ("Intensity Histogram Median", [218, 7468, 7478]),
    },
    "IntensityHistogramMedianAbsoluteDeviation": {
        "4RNL": ("Intensity Histogram Median Absolute Deviation", [218, 7468, 7478]),
    },
    "IntensityHistogramMinimumGradient": {
        "VQB3": ("Intensity Histogram Minimum Gradient", [218, 7468, 7478]),
    },
    "IntensityHistogramMinimumGradientGrayLevel": {
        "RHQZ": ("Intensity Histogram Minimum Gradient Gray Level", [218, 7468, 7478]),
    },
    "IntensityHistogramMinimumGrayLevel": {
        "1PR8": ("Intensity Histogram Minimum Gray Level", [218, 7468, 7478]),
    },
    "IntensityHistogramMode": {
        "AMMC": ("Intensity Histogram Mode", [218, 7468, 7478]),
    },
    "IntensityHistogramQuartileCoefficientOfDispersion": {
        "SLWD": (
            "Intensity Histogram Quartile Coefficient of Dispersion",
            [218, 7468, 7478],
        ),
    },
    "IntensityHistogramRange": {
        "5Z3W": ("Intensity Histogram Range", [218, 7468, 7478]),
    },
    "IntensityHistogramRobustMeanAbsoluteDeviation": {
        "WRZB": (
            "Intensity Histogram Robust Mean Absolute Deviation",
            [218, 7468, 7478],
        ),
    },
    "IntensityHistogramSkewness": {
        "88K1": ("Intensity Histogram Skewness", [218, 7468, 7478]),
    },
    "IntensityHistogramUniformity": {
        "BJ5W": ("Intensity Histogram Uniformity", [218, 7468, 7478]),
    },
    "IntensityHistogramVariance": {
        "CH89": ("Intensity Histogram Variance", [218, 7468, 7478]),
    },
    "InverseDifferenceMomentOfGLCM": {
        "WF0Z": ("Inverse Difference Moment of GLCM", [218, 7467, 7468]),
    },
    "InverseDifferenceOfGLCM": {
        "IB1Z": ("Inverse Difference of GLCM", [218, 7467, 7468]),
    },
    "InverseVarianceOfGLCM": {
        "E8JP": ("Inverse Variance of GLCM", [218, 7467, 7468]),
    },
    "JointAverageOfGLCM": {
        "60VM": ("Joint Average of GLCM", [218, 7467, 7468]),
    },
    "JointEntropyOfGLCM": {
        "TU9B": ("Joint Entropy of GLCM", [218, 7467, 7468]),
    },
    "JointMaximumOfGLCM": {
        "GYBY": ("Joint Maximum of GLCM", [218, 7467, 7468]),
    },
    "JointVarianceOfGLCM": {
        "UR99": ("Joint Variance of GLCM", [218, 7467, 7468]),
    },
    "LargeDistanceEmphasis": {
        "MB4I": ("Large Distance Emphasis", [218, 7468, 7479]),
    },
    "LargeDistanceHighGreyLevelEmphasis": {
        "KLTH": ("Large Distance High Grey Level Emphasis", [218, 7468, 7479]),
    },
    "LargeDistanceLowGreyLevelEmphasis": {
        "A7WM": ("Large Distance Low Grey Level Emphasis", [218, 7468, 7479]),
    },
    "LargeZoneEmphasis": {
        "48P8": ("Large Zone Emphasis", [218, 7468, 7476]),
    },
    "LargeZoneHighGrayLevelEmphasis": {
        "J17V": ("Large Zone High Gray Level Emphasis", [218, 7468, 7476]),
    },
    "LargeZoneLowGrayLevelEmphasis": {
        "YH51": ("Large Zone Low Gray Level Emphasis", [218, 7468, 7476]),
    },
    "LeastAxisIn3DLength": {
        "7J51": ("Least Axis in 3D Length", [218, 6165, 7469, 7470, 7477]),
    },
    "LongRunHighGrayLevelEmphasis": {
        "3KUM": ("Long Run High Gray Level Emphasis", [218, 7468, 7475]),
    },
    "LongRunLowGrayLevelEmphasis": {
        "IVPO": ("Long Run Low Gray Level Emphasis", [218, 7468, 7475]),
    },
    "LongRunsEmphasis": {
        "W4KF": ("Long Runs Emphasis", [218, 7468, 7475]),
    },
    "LowDependenceEmphasis": {
        "SODN": ("Low dependence emphasis", [218, 7468, 7501]),
    },
    "LowDependenceHighGreyLevelEmphasis": {
        "JA6D": ("Low dependence high grey level emphasis", [218, 7468, 7501]),
    },
    "LowDependenceLowGreyLevelEmphasis": {
        "EQ3F": ("Low dependence low grey level emphasis", [218, 7468, 7501]),
    },
    "LowGrayLevelRunEmphasis": {
        "V3SW": ("Low Gray Level Run Emphasis", [218, 7468, 7475]),
    },
    "LowGrayLevelZoneEmphasis": {
        "XMSY": ("Low Gray Level Zone Emphasis", [218, 7468, 7476]),
    },
    "LowGreyLevelCountEmphasis": {
        "TL9H": ("Low grey level count emphasis", [218, 7468, 7501]),
    },
    "LowGreyLevelZoneEmphasis": {
        "S1RA": ("Low Grey Level Zone Emphasis", [218, 7468, 7479]),
    },
    "MajorAxisIn3DLength": {
        "TDIC": ("Major Axis in 3D Length", [218, 6165, 7469, 7470, 7477]),
    },
    "Maximum3DDiameterOfAMesh": {
        "L0JK": ("Maximum 3D Diameter of a Mesh", [218, 6165, 7469, 7470, 7477]),
    },
    "MinorAxisIn3DLength": {
        "P9VJ": ("Minor Axis in 3D Length", [218, 6165, 7469, 7470, 7477]),
    },
    "MoranIIndex": {
        "N365": ("Moran's I Index", [218, 7477]),
    },
    "NormalizedGrayLevelNonuniformityInRuns": {
        "OVBL": ("Normalized Gray Level Nonuniformity in Runs", [218, 7468, 7475]),
    },
    "NormalizedGrayLevelNonuniformityOfSizeZoneCounts": {
        "Y1RO": (
            "Normalized Gray Level Nonuniformity of Size Zone Counts",
            [218, 7468, 7476],
        ),
    },
    "NormalizedGreyLevelNonUniformityOfDistanceZoneCounts": {
        "7HP3": (
            "Normalized Grey Level Non-uniformity of Distance Zone Counts",
            [218, 7468, 7479],
        ),
    },
    "NormalizedGreyLevelNonUniformityOfNGLDM": {
        "5SPA": ("Normalized grey level non-uniformity of NGLDM", [218, 7468, 7501]),
    },
    "NormalizedInverseDifferenceMomentOfGLCM": {
        "1QCO": ("Normalized Inverse Difference Moment of GLCM", [218, 7467, 7468]),
    },
    "NormalizedInverseDifferenceOfGLCM": {
        "NDRX": ("Normalized Inverse Difference of GLCM", [218, 7467, 7468]),
    },
    "NormalizedRunLengthNonuniformity": {
        "IC23": ("Normalized Run Length Nonuniformity", [218, 7468, 7475]),
    },
    "NormalizedZoneDistanceNonUniformity": {
        "IATH": ("Normalized Zone Distance Non-uniformity", [218, 7468, 7479]),
    },
    "NormalizedZoneSizeNonuniformity": {
        "VB3A": ("Normalized Zone Size Nonuniformity", [218, 7468, 7476]),
    },
    "RunEntropy": {
        "HJ9O": ("Run Entropy", [218, 7468, 7475]),
    },
    "RunLengthNonuniformity": {
        "W92Y": ("Run Length Nonuniformity", [218, 7468, 7475]),
    },
    "RunLengthVariance": {
        "SXLW": ("Run Length Variance", [218, 7468, 7475]),
    },
    "RunPercentage": {
        "9ZK5": ("Run Percentage", [218, 7468, 7475]),
    },
    "SecondMeasureOfInformationCorrelationOfGLCM": {
        "JN9H": (
            "Second Measure of Information Correlation of GLCM",
            [218, 7467, 7468],
        ),
    },
    "ShortRunHighGrayLevelEmphasis": {
        "GD3A": ("Short Run High Gray Level Emphasis", [218, 7468, 7475]),
    },
    "ShortRunLowGrayLevelEmphasis": {
        "HTZT": ("Short Run Low Gray Level Emphasis", [218, 7468, 7475]),
    },
    "ShortRunsEmphasis": {
        "22OV": ("Short Runs Emphasis", [218, 7468, 7475]),
    },
    "SizeZonePercentage": {
        "P30P": ("Size Zone Percentage", [218, 7468, 7476]),
    },
    "SmallDistanceEmphasis": {
        "0GBI": ("Small Distance Emphasis", [218, 7468, 7479]),
    },
    "SmallDistanceHighGreyLevelEmphasis": {
        "DKNJ": ("Small Distance High Grey Level Emphasis", [218, 7468, 7479]),
    },
    "SmallDistanceLowGreyLevelEmphasis": {
        "RUVG": ("Small Distance Low Grey Level Emphasis", [218, 7468, 7479]),
    },
    "SmallZoneEmphasis": {
        "5QRC": ("Small Zone Emphasis", [218, 7468, 7476]),
    },
    "SmallZoneHighGrayLevelEmphasis": {
        "HW1V": ("Small Zone High Gray Level Emphasis", [218, 7468, 7476]),
    },
    "SmallZoneLowGrayLevelEmphasis": {
        "5RAI": ("Small Zone Low Gray Level Emphasis", [218, 7468, 7476]),
    },
    "SphericalDisproportion": {
        "KRCK": ("Spherical Disproportion", [218, 7477]),
    },
    "Sphericity": {
        "QCFX": ("Sphericity", [218, 7477]),
    },
    "StrengthOfNGTDM": {
        "1X9X": ("Strength of NGTDM", [218, 7468, 7500]),
    },
    "SumAverageOfGLCM": {
        "ZGXS": ("Sum Average of GLCM", [218, 7467, 7468]),
    },
    "SumEntropyOfGLCM": {
        "P6QZ": ("Sum Entropy of GLCM", [218, 7467, 7468]),
    },
    "SumVarianceOfGLCM": {
        "OEEB": ("Sum Variance of GLCM", [218, 7467, 7468]),
    },
    "SurfaceAreaOfMesh": {
        "C0JK": ("Surface Area of Mesh", [218, 7469, 7471, 7477]),
    },
    "SurfaceToVolumeRatio": {
        "2PR5": ("Surface to Volume Ratio", [218, 7477]),
    },
    "VolumeDensityInApproximateEnclosingEllipsoid": {
        "6BDE": ("Volume Density in Approximate Enclosing Ellipsoid", [218, 7477]),
    },
    "VolumeDensityInConvexHull": {
        "R3ER": ("Volume Density in Convex Hull", [218, 7477]),
    },
    "VolumeDensityInFrameOfReferenceAxisAlignedBoundingBox": {
        "PBX1": (
            "Volume Density in Frame of Reference Axis Aligned Bounding Box",
            [218, 7477],
        ),
    },
    "VolumeDensityInMinimumVolumeEnclosingEllipsoid": {
        "SWZ1": ("Volume Density in Minimum Volume Enclosing Ellipsoid", [218, 7477]),
    },
    "VolumeDensityInOrientedMinimumBoundingBox": {
        "ZH1A": ("Volume Density in Oriented Minimum Bounding Box", [218, 7477]),
    },
    "VolumeFromVoxelSummation": {
        "YEKZ": ("Volume from Voxel Summation", [218, 7469, 7472, 7477]),
    },
    "VolumeOfMesh": {
        "RNU0": ("Volume of Mesh", [218, 7469, 7472, 7477]),
    },
    "ZoneDistanceEntropy": {
        "GBDU": ("Zone Distance Entropy", [218, 7468, 7479]),
    },
    "ZoneDistanceNonUniformity": {
        "V294": ("Zone Distance Non-uniformity", [218, 7468, 7479]),
    },
    "ZoneDistanceVariance": {
        "7WT1": ("Zone Distance Variance", [218, 7468, 7479]),
    },
    "ZoneSizeEntropy": {
        "GU8N": ("Zone Size Entropy", [218, 7468, 7476]),
    },
    "ZoneSizeNonuniformity": {
        "4JP3": ("Zone Size Nonuniformity", [218, 7468, 7476]),
    },
    "ZoneSizeVariance": {
        "3NSA": ("Zone Size Variance", [218, 7468, 7476]),
    },
}
