# Auto-generated by pydicom-data-sr
# -*- coding: utf-8 -*-

from typing import Dict, List, Tuple


from sr.tables._concepts_BARI import concepts_BARI
from sr.tables._concepts_DCM import concepts_DCM
from sr.tables._concepts_FMA import concepts_FMA
from sr.tables._concepts_IBSI import concepts_IBSI
from sr.tables._concepts_ITIS_TSN import concepts_ITIS_TSN
from sr.tables._concepts_LN import concepts_LN
from sr.tables._concepts_MDC import concepts_MDC
from sr.tables._concepts_MSH import concepts_MSH
from sr.tables._concepts_NCIt import concepts_NCIt
from sr.tables._concepts_NDC import concepts_NDC
from sr.tables._concepts_NEU import concepts_NEU
from sr.tables._concepts_PUBCHEM_CID import concepts_PUBCHEM_CID
from sr.tables._concepts_RADLEX import concepts_RADLEX
from sr.tables._concepts_RXNORM import concepts_RXNORM
from sr.tables._concepts_SCT import concepts_SCT
from sr.tables._concepts_UCUM import concepts_UCUM
from sr.tables._concepts_UMLS import concepts_UMLS


concepts: Dict[str, Dict[str, Dict[str, Tuple[str, List[int]]]]] = {
    "BARI": concepts_BARI,
    "DCM": concepts_DCM,
    "FMA": concepts_FMA,
    "IBSI": concepts_IBSI,
    "ITIS_TSN": concepts_ITIS_TSN,
    "LN": concepts_LN,
    "MDC": concepts_MDC,
    "MSH": concepts_MSH,
    "NCIt": concepts_NCIt,
    "NDC": concepts_NDC,
    "NEU": concepts_NEU,
    "PUBCHEM_CID": concepts_PUBCHEM_CID,
    "RADLEX": concepts_RADLEX,
    "RXNORM": concepts_RXNORM,
    "SCT": concepts_SCT,
    "UCUM": concepts_UCUM,
    "UMLS": concepts_UMLS,
}
