# Auto-generated by pydicom-data-sr
# -*- coding: utf-8 -*-

concepts_NEU = {
    "AnteriorThalamicRadiation": {
        "1726": ("anterior thalamic radiation", [7702, 7710, 8134]),
    },
    "ArcuateFasciculus": {
        "2063": ("arcuate fasciculus", [7703, 7710, 8134]),
    },
    "CorticobulbarTract": {
        "1319": ("corticobulbar tract", [7702, 7710, 8134]),
    },
    "CorticospinalTract": {
        "1320": ("corticospinal tract", [7702, 7710, 8134]),
    },
    "InferiorOpticRadiationMeyerLoop": {
        "1466": ("inferior optic radiation (Meyer's loop)", [7702, 7710, 8134]),
    },
    "InferiorThalamicRadiation": {
        "2082": ("inferior thalamic radiation", [7702, 7710, 8134]),
    },
    "PosteriorThalamicRadiation": {
        "2083": ("posterior thalamic radiation", [7702, 7710, 8134]),
    },
    "StriaTerminalis": {
        "286": ("stria terminalis", [7704, 7710, 8134]),
    },
    "SuperiorLongitudinalFasciculus": {
        "2080": ("superior longitudinal fasciculus", [7703, 7710, 8134]),
    },
    "SuperiorOpticRadiationBaumLoop": {
        "3473": ("superior optic radiation (Baum's loop)", [7702, 7710, 8134]),
    },
    "SuperiorThalamicRadiation": {
        "2081": ("superior thalamic radiation", [7702, 7710, 8134]),
    },
}
