# Auto-generated by pydicom-data-sr
# -*- coding: utf-8 -*-

from typing import Dict, List, Tuple


concepts_RXNORM: Dict[str, Dict[str, Tuple[str, List[int]]]] = {
    "MangafodipirTrisodium": {
        "236987": ("Mangafodipir trisodium", [12, 3850]),
    },
}
